/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;
        import net.sf.jasperreports.engine.JRResultSetDataSource;
        import net.sf.jasperreports.engine.JasperCompileManager;
        import net.sf.jasperreports.engine.JasperFillManager;
        import net.sf.jasperreports.engine.JasperPrint;
        import net.sf.jasperreports.engine.JasperReport;
        import net.sf.jasperreports.swing.JRViewer;


/**
 *
 * @author EDYKURNIAWAN-PC
 */
public class Barang extends javax.swing.JFrame {
    Connection koneksi;
    PreparedStatement pst;
    ResultSet rst;
    /**
     * Creates new form Login
     */
    public Barang() {
        initComponents();
        koneksi=database.koneksiDB();
        update_tabel();
        delay();
    }
    
     public void delay(){
    Thread clock=new Thread(){
        public void run(){
            for(;;){
                Calendar cal=Calendar.getInstance();
                SimpleDateFormat format=new SimpleDateFormat("HH:mm:ss");
                SimpleDateFormat format2=new SimpleDateFormat("dd-MM-yyyy");
                jjam.setText(format.format(cal.getTime()));
                jtgl.setText(format2.format(cal.getTime()));
                
            try { sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
        }
      };
    clock.start();
    }
    
    public void update_tabel(){
       try {
        String sql="select * from barang";
        pst=koneksi.prepareStatement(sql);
        rst=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rst));
       } catch (Exception e){ JOptionPane.showMessageDialog(null, e);}        
    }
    
    private void clsr(){
        jsatuan.setText("");
        jkode.setText("");
        jnama.setText("");
        jstok.setText("");
        jharga.setText("");
    }
    
    private void simpan(){
     try {
            String sql="insert into barang (Kode_Barang,Nama_Barang,Stok,Satuan,Harga) value (?,?,?,?,?)";
            pst=koneksi.prepareStatement(sql);
            pst.setString(1, jkode.getText());
            pst.setString(2, jnama.getText());
            pst.setString(3, jstok.getText());
            pst.setString(4, jsatuan.getText());
            pst.setString(5, jharga.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
           update_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jsatuan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jkode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jstok = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jharga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jjam = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Point Of Sales");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 30, 200, 50);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("____________");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 220, 40);

        jPanel5.setBackground(new java.awt.Color(116, 185, 255));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Barang");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(50, 10, 150, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barang.png"))); // NOI18N
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 0, 40, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 110, 250, 50);

        jPanel6.setBackground(new java.awt.Color(41, 128, 185));
        jPanel6.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3);
        jLabel3.setBounds(50, 10, 150, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_lock_96px_1.png"))); // NOI18N
        jPanel6.add(jLabel8);
        jLabel8.setBounds(10, 0, 40, 50);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 480, 250, 50);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Laporan Transaksi");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 270, 170, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ledger_96px.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 260, 35, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/store.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 165, 35, 40);

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Laporan Barang");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 220, 150, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_report_card_96px.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 210, 35, 50);

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Transaksi");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 170, 150, 30);

        jLabel21.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Edy Kurniawan");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel21);
        jLabel21.setBounds(70, 70, 100, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 532));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel10.setText("Satuan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 170, 50, 30);

        jsatuan.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jsatuan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jsatuan);
        jsatuan.setBounds(70, 170, 100, 30);

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel16.setText("Data Barang :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(260, 10, 110, 40);

        jkode.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jkode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jkode);
        jkode.setBounds(70, 10, 110, 30);

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel17.setText("Nama");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 50, 60, 30);

        jnama.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jnama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jnama);
        jnama.setBounds(70, 50, 170, 30);

        jLabel18.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel18.setText("Stok");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 90, 40, 30);

        jstok.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jstok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jstok);
        jstok.setBounds(70, 90, 40, 30);

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel19.setText("Harga");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 130, 40, 30);

        jharga.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jharga.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jharga);
        jharga.setBounds(70, 130, 70, 30);

        jButton1.setBackground(new java.awt.Color(52, 152, 219));
        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jButton1.setText("Edit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 280, 90, 40);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(260, 50, 460, 330);

        jLabel20.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel20.setText("Kode");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 10, 60, 30);

        jButton2.setBackground(new java.awt.Color(52, 152, 219));
        jButton2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_close_96px.png"))); // NOI18N
        jButton2.setText("Simpan");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(80, 220, 90, 40);

        jButton3.setBackground(new java.awt.Color(52, 152, 219));
        jButton3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(140, 280, 90, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 162, 710, 370));

        jPanel3.setBackground(new java.awt.Color(41, 128, 185));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Form Data Barang __________________");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 710, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jjam.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jjam);
        jjam.setBounds(570, 10, 130, 40);

        jLabel22.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Aplikasi Transaksi Penjualan");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel22);
        jLabel22.setBounds(10, 10, 170, 40);

        jtgl.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jtgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtgl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jtgl);
        jtgl.setBounds(480, 10, 120, 40);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 710, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          try {
    int row=jTable1.getSelectedRow();
    String tabel_klik=(jTable1.getModel().getValueAt(row, 0).toString());
    String sql="select * from barang where Kode_Barang='"+tabel_klik+"'";
    pst=koneksi.prepareStatement(sql);
    rst=pst.executeQuery();
    if (rst.next()) {
    String data1=rst.getString(("Kode_Barang"));
    jkode.setText(data1);
    String data2=rst.getString(("Nama_Barang"));
    jnama.setText(data2);
    String data3=rst.getString(("Stok"));
    jstok.setText(data3);
    String data4=rst.getString(("Satuan"));
    jsatuan.setText(data4);
    String data5=rst.getString(("Harga"));
    jharga.setText(data5);
    }
}catch (Exception e) {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
         String value1=jnama.getText();
          String value2=jkode.getText();
          String value3=jstok.getText();
          String value4=jsatuan.getText();
          String value5=jharga.getText();
         String sql="update barang set Nama_Barang='"+value1+"' ,Stok='"+value3+"' ,Satuan='"+value4+"' ,Harga='"+value5+"' where Kode_Barang='"+value2+"'";
         pst=koneksi.prepareStatement(sql);
         pst.execute();
         JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
        update_tabel();
        clsr();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try { 
    String sql="delete from barang where Kode_Barang=?";
    pst=koneksi.prepareStatement(sql);
    pst.setString(1, jkode.getText());
    pst.execute();
    JOptionPane.showMessageDialog(null, "Data Terhapus");
    }catch (Exception e) {JOptionPane.showMessageDialog(null, e);} 
        update_tabel();
        clsr();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        simpan();
        clsr();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new Transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         try {
        String path="src/pos/barang.jasper";
        Map parameter = new HashMap();
        JasperPrint print = JasperFillManager.fillReport(path,parameter, koneksi);
        JasperViewer.viewReport(print, false);
      } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada"+ex);
      }   
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
        String path="src/pos/transaksi.jasper";
        Map parameter = new HashMap();
        JasperPrint print = JasperFillManager.fillReport(path,parameter, koneksi);
        JasperViewer.viewReport(print, false);
      } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada"+ex);
      }  
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jharga;
    private javax.swing.JLabel jjam;
    private javax.swing.JTextField jkode;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jsatuan;
    private javax.swing.JTextField jstok;
    private javax.swing.JLabel jtgl;
    // End of variables declaration//GEN-END:variables
}
